more_display_options
deepcharles/ruptures pull request #160
Opened 2021-05-22 12:14 UTC by earthgecko

Firstly thanks for a cool library.  The following proposed change is cosmetic only.

The current `display` plot of the `computed_chg_pts` renders the dashed vertical dashed lines with `linewidth=3` and no alpha.  This results in the dashed vertical lines overlaying the signal and obscuring it.

```
rpt.display(signal, results, computed_chg_pts, figsize=(8, 4))
```
![image](https://user-images.githubusercontent.com/96679/119225697-36929380-bafd-11eb-9cd3-720669f2115c.png)
**Please note**  these example plots are **not broken**, they are using a modified `results` list with only results from a specific window plotted, they are just highlighting a specific change point in a defined period, hence no leading change points or trailing change points are plotted.

The proposed change allows the user to pass additional arguments that allow the user to format the `computed_chg_pts` axvline parameters to overcome this resulting in a clearer visualisation of the change point and the signal.

```
rpt.display(
    signal, results, computed_chg_pts, computed_chg_pts_linewidth=1,
    computed_chg_pts_alpha=0.3, figsize=(8, 4))
```
![image](https://user-images.githubusercontent.com/96679/119225942-98073200-bafe-11eb-959e-8192283ba73c.png)

The change maintains the current format as the default behaviour and is therefore backwards compatible.

2021-05-24 07:27 UTC, deepcharles requested changes
Many thanks for this PR. Can you correct the docstring as mentioned in the review? Then it will be ok.

2021-05-24 07:27 UTC, deepcharles commented on src/ruptures/show/display.py
> +        computed_chg_pts_alpha (list, optional): alpha for computed_chg_pts_linestyle.
Can you update the highlighted docstrings to the following ?

```
computed_chg_pts_color (str, optional): color of the lines indicating the computed_chg_pts. Defaults to "k".
computed_chg_pts_linewidth (int, optional): linewidth of the lines indicating the computed_chg_pts. Defaults to 3.
computed_chg_pts_linestyle (str, optional): linestyle of the lines indicating the computed_chg_pts. Defaults to "--".
computed_chg_pts_alpha (float, optional): alpha of the lines indicating the computed_chg_pts. Defaults to "1.0".
```

2021-05-24 07:33 UTC, deepcharles commented on src/ruptures/show/display.py
> +        color = (
Also, can you replace this by
``` 
# color of the lines indicating the computed_chg_pts
color = computed_chg_pts_color
```

The CI spread it on several lines for some reason but this makes the code coverage fail.

2021-05-24 09:00 UTC, earthgecko commented
Hi @deepcharles done I think.  I wrapped the docstrings too as the function comment is wrapped.

2021-05-24 09:52 UTC, earthgecko commented
Added to tests and I think I resolved codecov no tests for color, etc by using the function arguments directly, rather than redeclaring them.

2021-05-24 09:56 UTC, deepcharles commented
very nice, I'll take a look

2021-06-09 07:21 UTC, deepcharles approved these changes

2021-06-09 07:22 UTC, merged

2021-06-09 07:22 UTC, deepcharles commented
Sorry, I forgot to merge. Thanks for your work.